version: '2'

services:
  elastic:
    build:
      context: './elastic'
      dockerfile: './Dockerfile'
#    ports:
#      - "10200:9200"
#      - "10300:9300"
    networks:
      base:
        ipv4_address: 10.5.0.2

  crawler:
    build:
      context: './crawler'
      dockerfile: './Dockerfile'
    networks:
      base:
        ipv4_address: 10.5.0.3

networks:
  base:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1