version: '3'

services:
  elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
        discovery.type: 'single-node'
        network.host: '0'
        ES_JAVA_OPTS: '-Xms200m -Xmx200m'
#    ports:
#      - 10200:9200

  crawler:
    environment:
      ESHOST: 'elastic'
      PGHOST: 'postgres'
#     Provide this variable with the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: 'wishlist'
    build:
      context: './crawler'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
#     Provide this variable with the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: 'wishlist'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    environment:
      ESHOST: 'elastic'
      PGHOST: 'postgres'
#     Provide this variable with the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: 'wishlist'
    build:
      context: './api'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres
    ports:
#     Provide this variable with the .env file
      - ${PORT}:8080