version: '3'

services:
  elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
        discovery.type: 'single-node'
        network.host: '0'
        ES_JAVA_OPTS: '-Xms200m -Xmx200m'
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data:rw

  crawler:
    environment:
      ESHOST: 'elastic'
      PGHOST: 'postgres'
#     Provide this variable with the .env file
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wishlist'
    build:
      context: './crawler'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
#     Provide this variable with the .env file
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wishlist'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../data/postgres:/var/lib/postgresql/data
  api:
    environment:
      ESHOST: 'elastic'
      PGHOST: 'postgres'
#     Provide this variable with the .env file
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wishlist'
    build:
      context: './api'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres
#    ports:
#     Provide this variable with the .env file
#      - ${PORT}:8080

  swagger:
    environment:
      SWAGGER_JSON: '/swagger/config.json'
    build: './swagger'
    volumes:
      - ./swagger:/swagger

  nginx:
    build: './nginx'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - swagger
