version: '2'

services:
  elastic:
    build:
      context: './elastic'
      dockerfile: './Dockerfile'
    networks:
      base:
        ipv4_address: 172.16.238.2
#    ports:
#      - "10200:9200"
#      - "10300:9300"
#    networks:
#      base:
#        ipv4_address: 10.5.0.2

  crawler:
    environment:
      - DBHOST=172.16.238.2
    build:
      context: './crawler'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
    networks:
      base:
        ipv4_address: 172.16.238.3

#    networks:
#      base:
#        ipv4_address: 10.5.0.3

#networks:
#  base:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.5.0.0/16
#          gateway: 10.5.0.1

networks:
    base:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1