version: '3'

services:
  elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
      - network.host=0
    ports:
      - 10200:9200

  crawler:
    environment:
      - DBHOST=elastic
    build:
      context: './crawler'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic

  postgres:
    restart: always
    image: postgres:latest
    environment:
#     Provide this variable with the .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: 'wishlist'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    environment:
      - ELHOST=elastic
      - DBHOST=postgres
    build:
      context: './api'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres
    ports:
      - 8080:8080