version: '3'

services:
  elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
        discovery.type: 'single-node'
        network.host: '0'
        ES_JAVA_OPTS: '-Xms200m -Xmx200m'
    volumes:
        - ../data/elasticsearch:/usr/share/elasticsearch/data:rw

  crawler:
    environment:
      ESHOST: 'elastic'
      ESCOLL: 'products'
      PGHOST: 'postgres'
#     Provide this variable with the .env file
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wishlist'
      DEBUG: ${DEBUG}
    build:
      context: './crawler'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    environment:
#     Provide this variable with the .env file
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wishlist'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../data/postgres:/var/lib/postgresql/data

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      # The standard AMQP protocol port
      - 5674:5674
      # HTTP management UI
      - 15674:15674

  api:
    environment:
      ESHOST: 'elastic'
      ESCOLL: 'products'
      PGHOST: 'postgres'
      RMQHOST: 'rabbitmq'
      AUTHKEY: 'e5Grab2bwfcL6NWjTgEB'
      APPSECRET: 'e5Grab2bwfcL6NWjTgEB'
#     Provide this variable with the .env file
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wishlist'
      DEBUG: ${DEBUG}
    build:
      context: './api'
      dockerfile: './Dockerfile'
    depends_on:
      - elastic
      - postgres
      - rabbitmq
    ports:
#     Provide this variable with the .env file
      - ${PORT}:8080

  auth:
    environment:
      RMQHOST: 'rabbitmq'
      AUTHKEY: 'e5Grab2bwfcL6NWjTgEB'
    build:
      context: './auth_server'
      dockerfile: './Dockerfile'
    depends_on:
      - rabbitmq

  swagger:
    environment:
      SWAGGER_JSON: '/swagger/config.json'
    build: './swagger'
    volumes:
      - ./swagger:/swagger

  nginx:
    build: './nginx'
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - api
      - swagger
